In [1]:
import csv

# Define the header and data
header = ["emp_id", "emp_name", "designation", "salary"]
rows = [
    [101, "Aadhi", "Manager", 100000],
    [102, "Sam", "CEO", 200000],
    [103, "Harshitha", "Director", 100000],
    [104, "Sita", "Assistant", 50000],
    [105, "Ravi", "Executive", 75000]
]

# Write to CSV file
with open('employees.csv', mode='w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(header)
    writer.writerows(rows)

print("CSV file created successfully.")

CSV file created successfully.

In [2]:
new_records = [
    [106, "Anil", "Analyst", 60000],
    [107, "Geetha", "Clerk", 40000],
    [108, "Kiran", "Sales", 65000]
]

# Append to CSV file
with open('employees.csv', mode='a', newline='') as file:
    writer = csv.writer(file)
    writer.writerows(new_records)

print("New records appended to CSV file successfully.")

New records appended to CSV file successfully.

In [3]:
import pandas as pd

# Read the CSV file
df = pd.read_csv('employees.csv')

# Find the minimum salary
min_salary = df['salary'].min()
print(f"The minimum salary is: {min_salary}")

# Find the maximum salary
max_salary = df['salary'].max()
print(f"The maximum salary is: {max_salary}")

The minimum salary is: 40000
The maximum salary is: 200000

In [4]:
# Select required columns
df_selected = df[['emp_id', 'emp_name', 'salary']]

# Write to a new CSV file
df_selected.to_csv('selected_employees.csv', index=False)

print("Selected employees saved to 'selected_employees.csv'.")

In [5]:
# Define the data
text_data = [
    "101,Aadhi,Manager,100000",
    "102,Sam,CEO,200000",
    "103,Harshitha,Director,100000",
    "104,Sita,Assistant,50000",
    "105,Ravi,Executive,75000",
    "106,Anil,Analyst,60000",
    "107,Geetha,Clerk,40000",
    "108,Kiran,Sales,65000",
    "109,Meera,Technician,55000",
    "110,John,HR,70000"
]

# Write to a text file
with open('employees.txt', 'w') as file:
    for line in text_data:
        file.write(line + '\n')

print("Text file created successfully.")

Text file created successfully.

In [6]:
# Read the text file
with open('employees.txt', 'r') as file:
    lines = file.readlines()

# Process the data
data_list = []
for line in lines:
    emp_id, emp_name, designation, salary = line.strip().split(',')
    record = {
        "Emp_ID": int(emp_id),
        "Emp_Name": emp_name,
        "Designation": designation,
        "Salary": int(salary)
    }
    data_list.append(record)

print(data_list)

[{'Emp_ID': 101, 'Emp_Name': 'Aadhi', 'Designation': 'Manager', 'Salary': 100000}, {'Emp_ID': 102, 'Emp_Name': 'Sam', 'Designation': 'CEO', 'Salary': 200000}, {'Emp_ID': 103, 'Emp_Name': 'Harshitha', 'Designation': 'Director', 'Salary': 100000}, {'Emp_ID': 104, 'Emp_Name': 'Sita', 'Designation': 'Assistant', 'Salary': 50000}, {'Emp_ID': 105, 'Emp_Name': 'Ravi', 'Designation': 'Executive', 'Salary': 75000}, {'Emp_ID': 106, 'Emp_Name': 'Anil', 'Designation': 'Analyst', 'Salary': 60000}, {'Emp_ID': 107, 'Emp_Name': 'Geetha', 'Designation': 'Clerk', 'Salary': 40000}, {'Emp_ID': 108, 'Emp_Name': 'Kiran', 'Designation': 'Sales', 'Salary': 65000}, {'Emp_ID': 109, 'Emp_Name': 'Meera', 'Designation': 'Technician', 'Salary': 55000}, {'Emp_ID': 110, 'Emp_Name': 'John', 'Designation': 'HR', 'Salary': 70000}]

In [7]:
salaries = [record['Salary'] for record in data_list]

max_salary = max(salaries)
min_salary = min(salaries)

print(f"The maximum salary is: {max_salary}")
print(f"The minimum salary is: {min_salary}")

The maximum salary is: 200000
The minimum salary is: 40000

In [8]:
# List files in the current directory
!ls -l

total 16
-rw-r--r-- 1 root root  236 Aug 10 08:18 employees.csv
-rw-r--r-- 1 root root  237 Aug 10 08:20 employees.txt
drwxr-xr-x 1 root root 4096 Aug  8 13:25 sample_data
-rw-r--r-- 1 root root  154 Aug 10 08:18 selected_employees.csv

In [9]:
from google.colab import drive
drive.mount('/content/drive')

# Define the path to save files in Google Drive
drive_path = '/content/drive/My Drive/'

# Save the CSV and text files to Google Drive
with open(drive_path + 'employees.csv', 'w', newline='') as file:
    writer = csv.writer(file)
    writer.writerow(header)
    writer.writerows(rows + new_records)

df_selected.to_csv(drive_path + 'selected_employees.csv', index=False)

with open(drive_path + 'employees.txt', 'w') as file:
    for line in text_data:
        file.write(line + '\n')

Mounted at /content/drive